//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Manager { get; set; }
        public string Address { get; set; }
        public string Company_VOEN { get; set; }
        public string Bank_Name { get; set; }
        public string Settlement_Account { get; set; }
        public int Code { get; set; }
        public string Bank_VOEN { get; set; }
        public string Correspondent_Account { get; set; }
        public string Swift { get; set; }
        public DateTime Send_Date { get; set; }
    }
}
