//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICSDBContext : DbContext
    {
        public ICSDBContext()
            : base("name=ICSDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<About_Translate> About_Translate { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Address_Translate> Address_Translate { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Menus_Translate> Menus_Translate { get; set; }
        public virtual DbSet<Order_Services> Order_Services { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<SendEmailTo> SendEmailToes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Services_Translate> Services_Translate { get; set; }
        public virtual DbSet<Site_Contents> Site_Contents { get; set; }
        public virtual DbSet<Site_Images> Site_Images { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Slide_Translate> Slide_Translate { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<Steps_Translate> Steps_Translate { get; set; }
    }
}
