//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Services = new HashSet<Order_Services>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "***")]
        public string Company_Name { get; set; }
        [Required(ErrorMessage = "***")]
        public string VOEN { get; set; }
        [Required(ErrorMessage = "***")]
        [EmailAddress(ErrorMessage = "***")]
        public string Email { get; set; }
        [Required(ErrorMessage = "***")]
        public string Contact_Name { get; set; }
        [Required(ErrorMessage = "***")]
        public string Phone { get; set; }
        public string Additional_Order { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Services> Order_Services { get; set; }
    }
}
