//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "***")]
        [StringLength(50, ErrorMessage = "İstifadəçi adı 5-50 simvol aralığında ola bilər", MinimumLength = 5)]
        public string Username { get; set; }
        public string Password { get; set; }
        public string image { get; set; }
    }
}
